name: CI
on:
  issues:
    types: [opened]


jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:

    - name: see payload
      run: echo "$PAYLOAD"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - name: execute a github script
      uses: actions/github-script@7.0.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          username = process.env.USER;
          github.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: `@${username} Thanks for reporting!`
          })
      env:
        USER: ${{ github.actor }}